### ISSUE TITLE
I've decompiled a game but every scripts are corrupted :/

### ISSUE THREAD

**Issue by Ayfri** [bruvzg/gdsdecomp#10]
I don't know how to fix this and I don't know what I've done wrong 🤔

**Comment by cccreng** [comment]
I have the same problem, it doesn't decompile any scripts

**Comment by nikitalita** [comment]
Can you give us the engine version of the game(s) you're trying to decompile?

**Comment by cccreng** [comment]
ubuntu, godot version 3.2.0, using the 3.x fork of gdsdecomp, it decompiles majority of the stuff, but none of the scripts get decompiled.

**Comment by nikitalita** [comment]
You have to manually specify which scripts you want decompiled after extraction with the other menu option, it doesn't do it during extraction.

**Comment by cccreng** [comment]
thanks, and does you fork of gdsdecomp support directly decompiling scripts on extraction?

**Comment by nikitalita** [comment]
Yes it does. Use the branch my PR is on and follow the instructions in the PR, it's on Godot `master` but supports Godot 2-4 projects.
https://github.com/bruvzg/gdsdecomp/pull/19

**Comment by cccreng** [comment]
what does PR stand for?

**Comment by cccreng** [comment]
private repository?

**Comment by nikitalita** [comment]
Pull request, it's how you get changes into other forks on GitHub. It's the tab to the right of issues?

BTW, please be aware that full project export is currently a CLI-only option, it's not available via the menu yet.

**Comment by cccreng** [comment]
which branch do I use in your repository? (master, 3.2-backport, 3.2-cli-stuff, or 3.2)

**Comment by nikitalita** [comment]
![image](https://user-images.githubusercontent.com/69168929/115138338-53a8e380-9fe0-11eb-95d5-50039d71ec69.png)
So if you look at the PR, you'll see that I'm requesting a merge from my `4.0-nikitalita` branch.
![image](https://user-images.githubusercontent.com/69168929/115138349-763afc80-9fe0-11eb-8ef4-55d49ec87062.png)

**Comment by cccreng** [comment]
thanks

**Comment by nikitalita** [comment]
It supports building with the current Godot `master` (i.e. 4.x); it will not build with the `3.x` branch. Once built, it does support exporting Godot 2, 3, and 4 projects.

**Comment by cccreng** [comment]
thanks, that's all.... 👍

**Comment by cccreng** [comment]
error:
[Initial build] Compiling ==> modules/gdsdecomp/bytecode/bytecode_1a36141.cpp
[Initial build] Compiling ==> modules/gdsdecomp/bytecode/bytecode_1add52b.cpp
[Initial build] Compiling ==> modules/gdsdecomp/bytecode/bytecode_1ca61a3.cpp
[Initial build] Compiling ==> modules/gdsdecomp/bytecode/bytecode_216a8aa.cpp
[Initial build] Compiling ==> modules/gdsdecomp/bytecode/bytecode_2185c01.cpp
[Initial build] Compiling ==> modules/gdsdecomp/bytecode/bytecode_23381a5.cpp
[Initial build] Compiling ==> modules/gdsdecomp/bytecode/bytecode_23441ec.cpp
In file included from modules/gdsdecomp/utility/import_exporter.h:11,
                 from modules/gdsdecomp/register_types.cpp:12:
modules/gdsdecomp/utility/import_info.h: In member function 'int ImportInfo::get_import_loss_type() const':
modules/gdsdecomp/utility/import_info.h:160:46: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
  160 |   else if (importer == "wav" || version == 2 && importer == "sample") {
      |                                 ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
In file included from modules/gdsdecomp/utility/gdre_cli_main.h:5,
                 from modules/gdsdecomp/register_types.cpp:13:
modules/gdsdecomp/utility/gdre_settings.h: In member function 'void GDREOS<T>::_add_logger(Logger*)':
modules/gdsdecomp/utility/gdre_settings.h:37:38: error: there are no arguments to 'add_logger' that depend on a template parameter, so a declaration of 'add_logger' must be available [-fpermissive]
   37 |  void _add_logger(Logger *p_logger) {add_logger(p_logger);}
      |                                      ^~~~~~~~~~
modules/gdsdecomp/utility/gdre_settings.h:37:38: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
[Initial build] Compiling ==> modules/gdsdecomp/bytecode/bytecode_30c1229.cpp
[Initial build] Compiling ==> modules/gdsdecomp/bytecode/bytecode_31ce3c5.cpp
[Initial build] Compiling ==> modules/gdsdecomp/bytecode/bytecode_3ea6d9f.cpp
scons: *** [modules/gdsdecomp/register_types.linuxbsd.tools.64.o] Error 1
scons: building terminated because of errors.

**Comment by cccreng** [comment]
fixed: 
changed void _add_logger(Logger *p_logger) {add_logger(p_logger);}
to 
void _add_logger(Logger *p_logger) {_add_logger(p_logger);}
in gdre_settings.h

**Comment by Jimmio92** [comment]
When you decompile the scripts, you must match the version used to export. There's also a Godot export of this as a standalone app, no compiling into Godot is necessary to just use it. I just used it to completely recover a project I thought was gone forever.

**Comment by cccreng** [comment]
> When you decompile the scripts, you must match the version used to export. There's also a Godot export of this as a standalone app, no compiling into Godot is necessary to just use it. I just used it to completely recover a project I thought was gone forever.

Where do I find the standalone decompiler?

**Comment by Jimmio92** [comment]
The releases section of this project has builds for windows, linux, and mac. Github's layout blows, to be perfectly honest. It's tucked over on the right hand side instead of being a tab at the top and easily visible. https://github.com/bruvzg/gdsdecomp/releases
