### ISSUE TITLE
not building with Godot 3.3, 3.x nor master in linux

### ISSUE THREAD

**Issue by nesper8** [bruvzg/gdsdecomp#26]

**Comment by nikitalita** [comment]
Looks like we've drifted out of sync with master; try checking out godot @ b08dc1ea and running the build again.

**Comment by bruvzg** [comment]
Synced API changes, now `master` should build. In addition to multiple renames, Godot 4.0 have a new string based resource ID system (instead of resource indices in 3.x). `ResourceLoaderBinaryCompat` probably will need some future changes to work properly.

`3.x` branch should build with current `3.x` Godot, for Godot 3.3 use tag `v0.0.7`.

**Comment by nikitalita** [comment]
Full project export still currently works for Godot 2.x and 3.x, but any recently exported Godot 4.x projects will fail to be recovered correctly. I have a PR to add UUID support here: https://github.com/bruvzg/gdsdecomp/pull/27

**Comment by nesper8** [comment]
thank you
successfully builds now
